### ISSUE TITLE
New Step: Check a Marketo Lead's Activity

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#18]
### As a Crank user, I should be able to make assertions about specific events in a Lead's activity log.

**Proposed Step Name**: `Check a Marketo Lead's Activity`
**Proposed Step Expression**: `there should be an? (?<activityNameOrId>.+) activity for marketo lead (?<email>.+) in the last (?<minutes>\\d) minutes?`

**Proposed Step Fields**:
- `email` (type `EMAIL`), the email address of the Marketo Lead
- `activityNameOrId` (type `ANYSCALAR`), either an activity type ID (integer) or activity type name
- `minutes` (type `NUMBER`), represents the number of minutes prior to now to use when filtering the activity feed.
- `withAttributes` (type `MAP`, is optional), represents additional parameters that should be used to validate an event. The key in the object represents an attribute name and the value represents the expected value.

**UAT Target**
- [x] The optional `withAttributes` field should be used when filtering the list of activities returned by Marketo
- [x] Implementation should take care to check both `attributes` and `primaryAttributeValue` when considering `withAttributes` data on the activity list
- [x] This step should respond with an `error` if any pre-conditions fail, including:
  - [x] No lead exists for the given email address.
  - [x] No activity type found for given activity type name or ID
- [ ] This step should respond with a `failed` if all pre-conditions above are met, but there are no matching activities
  - [ ] And (for now) after a relevant failure message, print the raw activities as a JSON string in "pretty-print" format (e.g. `JSON.stringify(activities, null, 2);`)
    - e.g. `There was no matching %s activity for lead %s. Logged activities include:\n\n%s`,
- [x] This step should respond with a `passed` if one or more activities match the given criteria.

**Notes and References**
- The API client we use has not implemented the endpoint we need, but we can use the semi-private `_connection` object on the API client to make the appropriate call (similar to the delete lead step).
- https://developers.marketo.com/rest-api/lead-database/activities/
- https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Activities/getLeadActivitiesUsingGET

-----

### Example Usage

```yml
# Common Case
- step: Then there should be an Add to Nurture activity for Marketo Lead {{test.email}} in the last 5 minutes

# Activity ID Provided instead of Name
- step: There should be a 113 activity for Marketo Lead {{test.email}} in the last 5 minutes

# Single attribute provided
- step: there should be an Add to List activity for Marketo Lead {{test.email}} in the last 1 minute
  data:
    withAttributes:
      'List ID': 123

# Multiple attributes provided.
- step: then there should be a Change Status in SFDC Campaign activity for Marketo Lead {{test.email}} in the last 60 minutes
  data:
    withAttributes:
      'Campaign ID': 123
      'New Status': Attended
```
