### ISSUE TITLE
Field check using contains operator failed because it's currently case sensitive

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-marketo#23]
Upon checking, this same issue is still happening on Marketo cog and probably also happening on other cogs. This has been fixed in SalesForce cog and is still working as expected. 

**_Note:
It seems that other cogs are still not updated with the latest changes in SalesForce cog_**

**Repro Steps:**
1. Run the yml file.

```yml
scenario: Form Test validation with operators in Marketo
description: This test the smooth operators in Marketo

tokens:
  test:
    email: cjdeclaro@thisisjust.atomatest.com
    lastname: De Claro
    firstname: CJ
    company: Yeah corp
    title: Executive
    country: United States
    submit: button[type=submit]
  
steps:
- step: Navigate to http://go.automatoninc.com/Automatest-Live-Demo_Demo-Page-New-2019-Updated.html
- step: Fill out input[id=Email] with {{test.email}}
- step: Fill out input[id=Company] with {{test.company}}
- step: Fill out input[id=LastName] with {{test.lastname}}
- step: Fill out input[id=FirstName] with {{test.firstname}}
- step: Fill out select[id=Country] with {{test.country}}
- step: Submit the form by clicking {{test.submit}}
- waitFor: 60
  step: Validate that the email field on marketo lead {{test.email}} should not be cjdeclaro@atomatest.com
- step: Validate that the lastName field on marketo lead {{test.email}} should contain de
- step: Validate that the behavioralScore field on marketo lead {{test.email}} should be less than 100
```
![casesensitive](https://user-images.githubusercontent.com/54615569/70962407-136de400-20c0-11ea-9379-0e920adccdf9.PNG)

**Expected Result:**
Contains and Does not contain should not be case sensistive
