### ISSUE TITLE
New Step: Delete a Marketo Custom Object

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#34]
### As a Crank user, I should be able to delete Marketo custom objects.

**Proposed Step Name**: `Delete a Marketo Custom Object`
**Proposed Step Expression**: `delete the (?<name>.+) marketo custom object linked to lead (?<linkValue>.+)`

**Proposed Step Fields**:
- `name` (type `STRING`, required) Custom Object's display or API name
- `linkValue` (type `EMAIL`, required) Linked Lead's email address
- `dedupeFields`: (type `MAP`, optional) Key/value map whose keys are dedupe field names. Used to uniquely identify a single custom object in cases where many may be linked.

**UAT Target**
- [ ] Input Validation
  - [x] The step should respond with an error if the provided `name` does not correspond to the display name or API name of an existing Custom Object: `Error deleting %s: no such marketo custom object` (where is the`name`).
  - [x] The step should respond with an error if the resolved Custom Object metadata indicates that it is not linked to a lead object: `Error deleting %s linked to %s: this custom object isn't linked to leads`.
  - [x] The step should respond with an error if the query result (having provided `linkValue` and `dedupeFields` on the query) yields more than 1 record: `Error deleting %s linked to %s: more than one matching custom object was found. Please provide dedupe field values to specify which object`)
- [x] Other Responses
  - [x] Step should pass if the custom object was successfully deleted: `Successfully deleted %s linked to %s.`
  - [x] Step should respond with an error if any code-level or API-level errors were encountered during execution: `Error deleting %s: %s`

**Notes and References**
- The API client we use has not implemented the endpoint(s) we need, but we can use the semi-private `_connection` object on the API client to make the appropriate call (similar to the [delete lead step](https://github.com/run-crank/cog-marketo/blob/master/src/client/mixins/lead-aware.ts#L16)).
- Should use `idField`-mode deletion, using the retrieved `marketoGUID` value.
- [Conceptual API Docs for Custom Objects](https://developers.marketo.com/rest-api/lead-database/custom-objects/)
- [ Raw API Docs for Custom Objects](https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Custom_Objects/getCustomObjectsUsingGET)

-----

### Example Usage

```yml
- step: Create or update a Dev QA Alternative Link Field Object Marketo Custom Object linked to lead co@thisisjust.atomatest.com
  data:
    object:
      memberId: xyz
- step: Delete the devQAAlternativeLinkFieldObject_c Marketo Custom Object linked to lead co@thisisjust.atomatest.com
```
