### ISSUE TITLE
New Step: Check a field on a Marketo Custom Object

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#35]
### As a Crank user, I should be able to check field values on Marketo custom objects.

**Proposed Step Name**: `Check a field on a Marketo Custom Object`
**Proposed Step Expression**: `the (?<field>[a-zA-Z0-9_-]+) field on the (?<name>.+) marketo custom object linked to lead (?<linkValue>.+) should (?<operator>be less than|be greater than|be|contain|not be|not contain) (?<expectedValue>.+)`

**Proposed Step Fields**:
- `name`: (type `STRING`) Custom Object's display or API name
- `linkValue` (type `EMAIL`, required) Linked Lead's email address
- `field` (type `STRING`) The name of the field to check
- `operator`: (type `STRING`) Check Logic (be, not be, contain, not contain, be greater than, or be less than)
- `expectedValue`: (type `ANYSCALAR`) The expected value of the field
- `dedupeFields`: (type `MAP`, optional) Key/value map whose keys are dedupe field names. Used to uniquely identify a single custom object in cases where many may be linked.

**UAT Target**
- [x] Input Validation
  - [x] The step should respond with an error if the provided `name` does not correspond to the display name or API name of an existing Custom Object: `Error deleting %s: no such marketo custom object` (where `%s` is the provided `name`).
  - [x] The step should respond with an error if the resolved Custom Object metadata indicates that it is not linked to a lead object: `Error deleting %s linked to %s: this custom object isn't linked to leads`.
  - [x] The step should respond with an error if the query result (having provided `linkValue` and `dedupeFields` on the query) yields more than 1 record: Error checking %s linked to %s: more than one matching custom object was found. Please provide dedupe field values to specify which object`
 - [x] Handle Linked Field Automatically
   - [x] Custom objects can be linked to leads using any lead field. Although the `linkValue` field is the lead's email address, this step should automatically use the value of the link field on the given lead in order to query for the custom object.
- [ ] Responses
  - [x] Step should pass if the custom object was successfully found and the field value comparison is successful
  - [x] Step should fail if the custom object was successfully, but the field value comparison failed.
  - [ ] Step should respond with an error if the given `field` is not set on the object.
  - [ ] Step should respond with an error if no custom object could be found, given the provided `dedupeFields`
  - [x] Step should respond with an error if any code-level or API-level errors were encountered during execution: `There was an error checking the %s Marketo Custom object: %s`

**Notes and References**
- The API client we use has not implemented the endpoint(s) we need, but we can use the semi-private `_connection` object on the API client to make the appropriate call (similar to the [delete lead step](https://github.com/run-crank/cog-marketo/blob/master/src/client/mixins/lead-aware.ts#L16)).
- [Conceptual API Docs for Custom Objects](https://developers.marketo.com/rest-api/lead-database/custom-objects/)
- [ Raw API Docs for Custom Objects](https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Custom_Objects/getCustomObjectsUsingGET)

-----

### Example Usage

```yml
tokens:
  test.email: co@thisisjust.atomatest.com
  test.org: abc
  test.member: xyz

steps:
# Create a lead.
- step: Create or update a Marketo Lead
  data:
    lead:
      email: '{{test.email}}'
      organizationID: '{{test.org}}'

# Create a Custom Object linked to the above Lead.
- step: Create or update a Dev QA Alternative Link Field Object Marketo Custom Object linked to {{test.email}}
  data:
    object:
      memberId: '{{test.member}}'

# Check a regular field on the custom object.
- step: The memberId field on the devQAAlternativeLinkFieldObject_c Marketo Custom Object linked to {{test.email}} should be {{test.member}}

# Check the linked field on the custom object.
- step: The orgId field on the devQAAlternativeLinkFieldObject_c Marketo Custom Object linked to {{test.email}} should be {{test.org}}

# Delete the custom object and lead.
- step: Delete the devQAAlternativeLinkFieldObject_c Marketo Custom Object linked to {{test.email}}
- step: Delete the {{test.email}} Marketo Lead
```
