### ISSUE TITLE
Getting an error when checking a Marketo custom object field even if dedupe field value is provided

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-marketo#45]
## Repro Steps:
```yml
scenario: Custom Object Test
description: >
  Proves that this Cog can create and check custom objects that are
  linked to leads on the lead email field

tokens:
  test.obj: testCar_c
  test.email: testone@thisisjust.atomatest.com

steps:
- step: Given I create or update a Marketo Lead
  data: {lead: {email: '{{test.email}}'}}
- step: When I create or update a {{test.obj}} Marketo Custom Object linked to Lead {{test.email}}
  data:
    object:
      make: Honda
      model: Honda Jazz
      plateNumber: 56766
      color: blue
- step: And I create or update a {{test.obj}} Marketo Custom Object linked to Lead {{test.email}}
  data:
    object:
      make: Toyota
      model: Corolla Altis
      plateNumber: 57888
- step: Then the color field on the {{test.obj}} Marketo Custom Object linked to Lead {{test.email}} should be blue
  data:
    dedupeFields:
      make: Honda
      plateNumber: 56766
  
```

## Expected
Test should pass since I provided the dedupe fields values.

## Actual:
![image](https://user-images.githubusercontent.com/54615569/73354014-a3ae6400-42cf-11ea-9969-f40512e9131a.png)
