### ISSUE TITLE
It should show "Successfully updated" when user only updates a Marketo custom object

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-marketo#55]
## Repro Steps:
1. Run the yml scenario.
```yml
scenario: Custom Object - One-To-Many Object
description: >
  Proves that this Cog can create, check, and delete custom objects that are
  linked to leads on the lead email field (effectively a 1:1 custom object).

tokens:
  test.obj: devQAOne_To_ManyObject_c
  test.email: one-to-many@thisisjust.atomatest.com

steps:
- step: Given I create or update a Marketo Lead
  data: {lead: {email: '{{test.email}}'}}
- step: When I create or update a {{test.obj}} Marketo Custom Object linked to Lead {{test.email}}
  data:
    customObject:
      customPrimaryKey: GT123
      name: Anything
```
2. Run the **Create or Update a Marketo Custom Object**
- Custom Object's API name devQAOne_To_ManyObject_c
- Linked Lead's email address one-to-many@thisisjust.atomatest.com
- customObject object key customPrimaryKey
- customObject object value GT123
- Add another customObject field? Yes
- customObject object key name
- customObject object value Something
- Add another customObject field? No

## Actual Result:
It shows that the custom object is created. However, it only updates the custom object since there's already an existing custom object.
![image](https://user-images.githubusercontent.com/54615569/74424421-e1dd8300-4e8c-11ea-886e-52ec885ea275.png)

## Expected Result:
It should show "Successfully updated..."
