### ISSUE TITLE
Wrong custom object is being deleted

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-marketo#56]
## Repro Steps:
1. Run the yml scenario:
```yml
scenario: Custom Object - One-To-Many Object
description: >
  Proves that this Cog can create, check, and delete custom objects that are
  linked to leads on the lead email field (effectively a 1:1 custom object).

tokens:
  test.obj: devQAOne_To_ManyObject_c
  test.email: one-to-many@thisisjust.atomatest.com

steps:
- step: Given I create or update a Marketo Lead
  data: {lead: {email: '{{test.email}}'}}
- step: When I create or update a {{test.obj}} Marketo Custom Object linked to Lead {{test.email}}
  data:
    customObject:
      customPrimaryKey: GT123
      name: Anything
- step: And I create or update a {{test.obj}} Marketo Custom Object linked to Lead {{test.email}}
  data:
    customObject:
      customPrimaryKey: GT124
      name: Anything
```
2. Run **Create or Update a Marketo Custom Object** step
  - Custom Object's API name: devQAOne_To_ManyObject_c
  - Linked Lead's email address: one-to-many@thisisjust.atomatest.com
  - customObject object key: customPrimaryKey
  - customObject object value: GT123
  - Add another customObject field? Yes
  - customObject object key: name
  - customObject object value: Something
  - Add another customObject field? No
3. Run **Delete a Marketo Custom Object** step.
  - Custom Object's API name devQAOne_To_ManyObject_c
  - Linked Lead's email address one-to-many@thisisjust.atomatest.com
  - Add dedupeFields fields? Yes
  - dedupeFields object key name
  - dedupeFields object value Anything
  - Add another dedupeFields field? No

## Actual Result:
Wrong custom object is being deleted.
![image](https://user-images.githubusercontent.com/54615569/74423611-865ec580-4e8b-11ea-95d9-62a133a95d8f.png)

Before
![custom_objects_marketo (2)](https://user-images.githubusercontent.com/54615569/74423713-aabaa200-4e8b-11ea-9840-9416dd34f82a.PNG)

After deleting:
![customobject_after](https://user-images.githubusercontent.com/54615569/74423727-b0b08300-4e8b-11ea-8a4a-bbf8cccc0ec4.PNG)

## Expected Result:
It should delete the custom object with the same name value.
