### ISSUE TITLE
New Step: Add Marketo Lead to Smart Campaign

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-marketo#6]
### As a Crank user, I should be able to add a user to a Smart Campaign

**Proposed Step Name**: `Add Marketo Lead to Smart Campaign`
**Proposed Step Expression**: `add the (?<email>.+) marketo lead to smart campaign (?<campaign>.+)`

**Proposed Step Fields**:
- `email` (type `EMAIL`), the email address of the Hubspot Contact
- `campaign` (type `ANYSCALAR`), either the name of the smart campaign, or its numeric ID

**Notes**
- [ ] Just FYI: Marketo's API docs refer to this as "triggering a campaign" for a lead. We are inverting this in the step text so that the action is being performed on the lead (which is how all of our other steps are written)
- [ ] If the `campaign` provided is numeric, it should just use the numeric value when making the call to Marketo.
- [ ] If the `campaign` provided is non-numeric, it should first query Marketo for a campaign with the given name, then use its ID.
  - [ ] If more than one campaign is returned, an error should be returned `Can't add %s to %s: found more than one campaign with that name.`
  - [ ] If the Campaign returned has the property `isRequestable` set to `false`, then respond with an error message: `Cannot add lead to smart campaign %s. In order to test this campaign, you must add a "Campaign is Requested" trigger with "Source" set to "Web Service API"`
- [ ] If the API responds with an error indicating a similar error to the above (can't add lead to campaign due to a missing trigger), respond with the same error message.

**Reference**
- https://github.com/MadKudu/node-marketo/blob/master/lib/api/campaign.js#L12
- https://developers.marketo.com/rest-api/assets/smart-campaigns/#request
- It is currently impossible to check what campaigns a lead belongs to, although there is a proposed feature in the Ideas forum: https://nation.marketo.com/ideas/9230

-----

### Example Scenario

```yml
scenario: Add to Campaign UAT
description: Proves that the Add Marketo Lead to Smart Campaign step is working

tokens:
  test
    email: atommy@example.com

steps:
- step: Given I create or update a Marketo Lead
  data:
    lead:
      email: '{{test.email}}'
      middleName: 'Not Testing'
- step: When I add the {{test.email}} marketo lead to smart campaign Dev - QA - Set Field Value
- step: Then the middleName field on Marketo Lead {{test.email}} should be Testing
- step: Finally, delete the {{test.email}} Marketo Lead
```

^ Note: In our dev instance, you can check the error condition mentioned above using a different campaign name: `Dev - QA - Email Confirmation`
